version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - pytorch

sphinx:
  fail_on_warning: true
  # https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
  configuration: docs/conf.py